//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 01:35:39 PM CEST 
//


package xml.po;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xws.generated.po package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PaymentOrder_QNAME = new QName("http://www.ftn.uns.ac.rs/xws/xsd/paymentOrder", "paymentOrder");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xws.generated.po
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PaymentOrder }
     * 
     */
    public PaymentOrder createPaymentOrder() {
        return new PaymentOrder();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link PaymentOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/paymentOrder", name = "paymentOrder")
    public JAXBElement<PaymentOrder> createPaymentOrder(PaymentOrder value) {
        return new JAXBElement<PaymentOrder>(_PaymentOrder_QNAME, PaymentOrder.class, null, value);
    }

}
