//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 01:35:39 PM CEST 
//

@XmlSchema(namespace = "http://www.ftn.uns.ac.rs/xws/xsd/paymentOrder",
			elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
			xmlns = { @javax.xml.bind.annotation.XmlNs(prefix = "cmn", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/common"),
		@javax.xml.bind.annotation.XmlNs(prefix = "po", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/paymentOrder"),
			@javax.xml.bind.annotation.XmlNs(prefix = "pos", namespaceURI = "http://www.ftn.uns.ac.rs/xws/xsd/pos")})
package xml.po;
import javax.xml.bind.annotation.XmlSchema;

